# 开发环境配置
server:
  port: 8080

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/eagleeye_finance?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: root
      password: root

  data:
    redis:
      host: localhost
      port: 6379
      database: 0

  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    com.eagleeye: DEBUG

knife4j:
  production: false
